### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mozgeuzun** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#10]
New Release will be created according to https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by mozgeuzun** [comment]
I wrote the release description in detail, I will add it after the codes are pushed

**Comment by duyguiremhalac** [comment]
Photographs showing the final state of the project are provided for the description.

**Comment by NightSwindlerz** [comment]
Folders and directories are arranged.

**Comment by mozgeuzun** [comment]
We created the first release with the help of the members @duyguiremhalac @NightSwindlerz @KadirYldrm @aydandemirbuken @mozgeuzun
