### ISSUE TITLE
Project Poster Upload

### ISSUE THREAD

**Issue by duyguiremhalac** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#13]
Two poster designs will be uploaded. One of the posters should be in Çankaya University specified format and the other one is free design of the group. @mozgeuzun @NightSwindlerz

**Comment by NightSwindlerz** [comment]
The specialized poster has been done.

**Comment by mozgeuzun** [comment]
The free design poster has been done

**Comment by KadirYldrm** [comment]
added the github wiki poster page
