### ISSUE TITLE
Project Web Page Will Updated

### ISSUE THREAD

**Issue by duyguiremhalac** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#15]
Project web page will be updated for the harmony of the mobile application and web page designs. @NightSwindlerz

**Comment by mozgeuzun** [comment]
I added telegram QR to the website

**Comment by NightSwindlerz** [comment]
Project report link added and small changes has been done.
