### ISSUE TITLE
CENG 408 Presentation 

### ISSUE THREAD

**Issue by duyguiremhalac** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#16]
A presentation will be made about the works done in the project, the developments, the updates, the applications that have been tried. @mozgeuzun

**Comment by mozgeuzun** [comment]
I added new page called Project Presentation 408 on the wiki

**Comment by duyguiremhalac** [comment]
EE408 project presentation is added on the Project Presentation 408 page.

**Comment by duyguiremhalac** [comment]
EE408 project presentation is added on the Project Presentation 408 page.
