### ISSUE TITLE
Web App will be developed and push codes to the repo

### ISSUE THREAD

**Issue by mozgeuzun** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#18]
By creating a Web app using React, the codes of this app will be pushed to the repo.
The Web App must include:
Dynamic chatbot feature
Çankaya University official homepage

**Comment by NightSwindlerz** [comment]
Dynamic chatbot feature added to the web app via using React.

**Comment by KadirYldrm** [comment]
Çankaya uni web page added
