### ISSUE TITLE
Turkish Dataset for training

### ISSUE THREAD

**Issue by mozgeuzun** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#2]
Turkish wikipedia dataset, which was passed through the preprocessing stage, will be added to the project.

**Comment by NightSwindlerz** [comment]
Turkish wikipedia dataset was purified from HTML Tags and added to [Google Drive.](https://drive.google.com/file/d/1sW3Elj8eeKih23xWYu8KtO9WKCnwUNlZ/view?usp=sharing)
