### ISSUE TITLE
Updated Literature Review

### ISSUE THREAD

**Issue by mozgeuzun** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#3]
- Gpt4 language training table will be added to the Literature Review and information about Turkish language tuning will be given.
-  In addition, the Turkish question answering pipeline of the BERT model will be detailed.

**Comment by aydandemirbuken** [comment]
Literature review was updated. 

Gpt4 language training table was be added.

BERT Turkish model was explained.
