### ISSUE TITLE
Updated Literature Review Second Part

### ISSUE THREAD

**Issue by mozgeuzun** [CankayaUniversity/ceng-407-408-2022-2023-Turkish-ChatBot-System-for-Cankaya-University-using-Artificial-Intelligence#6]
- Question Answer Systems will be explained.
 
- QA Systems Evaluations will be included to take advantage of when preparing the test plan.

**Comment by duyguiremhalac** [comment]
Question Answer Systems and evaluations are explained in Literature Review page in 4th subpart.
